// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=js,json_types=true"
// @generated from file job.proto (syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf'
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv1'
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv1'

/**
 * Describes the file job.proto.
 */
export const file_job: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cglqb2IucHJvdG8iPwogUmV2b2tlTWVzc2FnZXNCeVNpZ25lckpvYlBheWxvYWQSCwoDZmlkGAEgASgNEg4KBnNpZ25lchgCIAEoDCI4CidVcGRhdGVOYW1lUmVnaXN0cnlFdmVudEV4cGlyeUpvYlBheWxvYWQSDQoFZm5hbWUYASABKAxiBnByb3RvMw',
  )

/**
 * @generated from message RevokeMessagesBySignerJobPayload
 */
export type RevokeMessagesBySignerJobPayload =
  Message<'RevokeMessagesBySignerJobPayload'> & {
    /**
     * @generated from field: uint32 fid = 1;
     */
    fid: number

    /**
     * @generated from field: bytes signer = 2;
     */
    signer: Uint8Array
  }

/**
 * @generated from message RevokeMessagesBySignerJobPayload
 */
export type RevokeMessagesBySignerJobPayloadJson = {
  /**
   * @generated from field: uint32 fid = 1;
   */
  fid?: number

  /**
   * @generated from field: bytes signer = 2;
   */
  signer?: string
}

/**
 * Describes the message RevokeMessagesBySignerJobPayload.
 * Use `create(RevokeMessagesBySignerJobPayloadSchema)` to create a new message.
 */
export const RevokeMessagesBySignerJobPayloadSchema: GenMessage<
  RevokeMessagesBySignerJobPayload,
  RevokeMessagesBySignerJobPayloadJson
> = /*@__PURE__*/ messageDesc(file_job, 0)

/**
 * @generated from message UpdateNameRegistryEventExpiryJobPayload
 */
export type UpdateNameRegistryEventExpiryJobPayload =
  Message<'UpdateNameRegistryEventExpiryJobPayload'> & {
    /**
     * @generated from field: bytes fname = 1;
     */
    fname: Uint8Array
  }

/**
 * @generated from message UpdateNameRegistryEventExpiryJobPayload
 */
export type UpdateNameRegistryEventExpiryJobPayloadJson = {
  /**
   * @generated from field: bytes fname = 1;
   */
  fname?: string
}

/**
 * Describes the message UpdateNameRegistryEventExpiryJobPayload.
 * Use `create(UpdateNameRegistryEventExpiryJobPayloadSchema)` to create a new message.
 */
export const UpdateNameRegistryEventExpiryJobPayloadSchema: GenMessage<
  UpdateNameRegistryEventExpiryJobPayload,
  UpdateNameRegistryEventExpiryJobPayloadJson
> = /*@__PURE__*/ messageDesc(file_job, 1)
